var annotated_dup =
[
    [ "app_state", "structapp__state.html", "structapp__state" ],
    [ "choco_string", "structchoco__string.html", "structchoco__string" ],
    [ "filesystem", "structfilesystem.html", "structfilesystem" ],
    [ "fs_utils", "structfs__utils.html", "structfs__utils" ],
    [ "input_snapshot", "structinput__snapshot.html", "structinput__snapshot" ],
    [ "keyboard_event", "structkeyboard__event.html", "structkeyboard__event" ],
    [ "keyboard_event_args", "structkeyboard__event__args.html", "structkeyboard__event__args" ],
    [ "linear_alloc", "structlinear__alloc.html", "structlinear__alloc" ],
    [ "memory_system", "structmemory__system.html", "structmemory__system" ],
    [ "mouse_event", "structmouse__event.html", "structmouse__event" ],
    [ "mouse_event_args", "structmouse__event__args.html", "structmouse__event__args" ],
    [ "platform_backend", "structplatform__backend.html", "structplatform__backend" ],
    [ "platform_context", "structplatform__context.html", "structplatform__context" ],
    [ "platform_vtable", "structplatform__vtable.html", "structplatform__vtable" ],
    [ "renderer_backend_context", "structrenderer__backend__context.html", "structrenderer__backend__context" ],
    [ "renderer_backend_shader", "structrenderer__backend__shader.html", "structrenderer__backend__shader" ],
    [ "renderer_backend_vao", "structrenderer__backend__vao.html", "structrenderer__backend__vao" ],
    [ "renderer_backend_vbo", "structrenderer__backend__vbo.html", "structrenderer__backend__vbo" ],
    [ "renderer_shader_vtable", "structrenderer__shader__vtable.html", "structrenderer__shader__vtable" ],
    [ "renderer_vao_vtable", "structrenderer__vao__vtable.html", "structrenderer__vao__vtable" ],
    [ "renderer_vbo_vtable", "structrenderer__vbo__vtable.html", "structrenderer__vbo__vtable" ],
    [ "ring_queue", "structring__queue.html", "structring__queue" ],
    [ "window_event", "structwindow__event.html", "structwindow__event" ],
    [ "window_event_args", "structwindow__event__args.html", "structwindow__event__args" ]
];