#include <stdint.h>
#include <stddef.h>

#include "engine/core/buffer_utils/buffer_utils.h"

#if defined(TEST_BUILD) || defined(DEBUG_BUILD)
#include <assert.h>
#include <stdbool.h>
#include "engine/base/choco_macros.h"

static void buffer_utils_assert_not_null(const void* ptr_);
#endif

#ifdef TEST_BUILD
static void test_buffer_utils_le_int16_t_get(void);
static void test_buffer_utils_le_int32_t_get(void);
static void test_buffer_utils_le_int64_t_get(void);
static void test_buffer_utils_le_uint16_t_get(void);
static void test_buffer_utils_le_uint32_t_get(void);
static void test_buffer_utils_le_uint64_t_get(void);
#endif

typedef union buffer_utils {
    char buff_char[8];
    int16_t buff_int16_t[4];
    int32_t buff_int32_t[2];
    int64_t buff_int64_t;
    uint16_t buff_uint16_t[4];
    uint32_t buff_uint32_t[2];
    uint64_t buff_uint64_t;
} buff_utils_t;

int16_t buffer_utils_le_int16_t_get(const char* buff_) {
#if defined(TEST_BUILD) || defined(DEBUG_BUILD)
    buffer_utils_assert_not_null(buff_);
#endif
    buff_utils_t convert;
    convert.buff_char[0] = buff_[0];
    convert.buff_char[1] = buff_[1];
    return convert.buff_int16_t[0];
}

int32_t buffer_utils_le_int32_t_get(const char* buff_) {
#if defined(TEST_BUILD) || defined(DEBUG_BUILD)
    buffer_utils_assert_not_null(buff_);
#endif
    buff_utils_t convert;
    convert.buff_char[0] = buff_[0];
    convert.buff_char[1] = buff_[1];
    convert.buff_char[2] = buff_[2];
    convert.buff_char[3] = buff_[3];
    return convert.buff_int32_t[0];
}

int64_t buffer_utils_le_int64_t_get(const char* buff_) {
#if defined(TEST_BUILD) || defined(DEBUG_BUILD)
    buffer_utils_assert_not_null(buff_);
#endif
    buff_utils_t convert;
    convert.buff_char[0] = buff_[0];
    convert.buff_char[1] = buff_[1];
    convert.buff_char[2] = buff_[2];
    convert.buff_char[3] = buff_[3];
    convert.buff_char[4] = buff_[4];
    convert.buff_char[5] = buff_[5];
    convert.buff_char[6] = buff_[6];
    convert.buff_char[7] = buff_[7];
    return convert.buff_int64_t;
}

uint16_t buffer_utils_le_uint16_t_get(const char* buff_) {
#if defined(TEST_BUILD) || defined(DEBUG_BUILD)
    buffer_utils_assert_not_null(buff_);
#endif
    buff_utils_t convert;
    convert.buff_char[0] = buff_[0];
    convert.buff_char[1] = buff_[1];
    return convert.buff_uint16_t[0];
}

uint32_t buffer_utils_le_uint32_t_get(const char* buff_) {
#if defined(TEST_BUILD) || defined(DEBUG_BUILD)
    buffer_utils_assert_not_null(buff_);
#endif
    buff_utils_t convert;
    convert.buff_char[0] = buff_[0];
    convert.buff_char[1] = buff_[1];
    convert.buff_char[2] = buff_[2];
    convert.buff_char[3] = buff_[3];
    return convert.buff_uint32_t[0];
}

uint64_t buffer_utils_le_uint64_t_get(const char* buff_) {
#if defined(TEST_BUILD) || defined(DEBUG_BUILD)
    buffer_utils_assert_not_null(buff_);
#endif
    buff_utils_t convert;
    convert.buff_char[0] = buff_[0];
    convert.buff_char[1] = buff_[1];
    convert.buff_char[2] = buff_[2];
    convert.buff_char[3] = buff_[3];
    convert.buff_char[4] = buff_[4];
    convert.buff_char[5] = buff_[5];
    convert.buff_char[6] = buff_[6];
    convert.buff_char[7] = buff_[7];
    return convert.buff_uint64_t;
}

#if defined(TEST_BUILD) || defined(DEBUG_BUILD)
static void NO_COVERAGE buffer_utils_assert_not_null(const void* ptr_) {
    assert(NULL != ptr_);
}
#endif

#ifdef TEST_BUILD
void test_buffer_utils(void) {
    test_buffer_utils_le_int16_t_get();
    test_buffer_utils_le_int32_t_get();
    test_buffer_utils_le_int64_t_get();
    test_buffer_utils_le_uint16_t_get();
    test_buffer_utils_le_uint32_t_get();
    test_buffer_utils_le_uint64_t_get();
}

// Generated by ChatGPT
static void NO_COVERAGE test_buffer_utils_le_int16_t_get(void) {
    {
        // 0
        const char buff[2] = { 0x00, 0x00 };
        const int16_t ret = buffer_utils_le_int16_t_get(buff);

        assert((int16_t)0 == ret);
    }
    {
        // positive: 0x1234
        const char buff[2] = { 0x34, 0x12 };
        const int16_t ret = buffer_utils_le_int16_t_get(buff);

        assert((int16_t)0x1234 == ret);
    }
    {
        // negative: -2 = 0xFFFE
        const char buff[2] = { (char)0xFE, (char)0xFF };
        const int16_t ret = buffer_utils_le_int16_t_get(buff);

        assert((int16_t)-2 == ret);
    }
    {
        // INT16_MIN = 0x8000
        const char buff[2] = { 0x00, (char)0x80 };
        const int16_t ret = buffer_utils_le_int16_t_get(buff);

        assert(INT16_MIN == ret);
    }
}

// Generated by ChatGPT
static void NO_COVERAGE test_buffer_utils_le_int32_t_get(void) {
    {
        // 0
        const char buff[4] = { 0x00, 0x00, 0x00, 0x00 };
        const int32_t ret = buffer_utils_le_int32_t_get(buff);

        assert((int32_t)0 == ret);
    }
    {
        // positive: 0x12345678
        const char buff[4] = { 0x78, 0x56, 0x34, 0x12 };
        const int32_t ret = buffer_utils_le_int32_t_get(buff);

        assert((int32_t)0x12345678 == ret);
    }
    {
        // negative: -2 = 0xFFFFFFFE
        const char buff[4] = { (char)0xFE, (char)0xFF, (char)0xFF, (char)0xFF };
        const int32_t ret = buffer_utils_le_int32_t_get(buff);

        assert((int32_t)-2 == ret);
    }
    {
        // INT32_MIN = 0x80000000
        const char buff[4] = { 0x00, 0x00, 0x00, (char)0x80 };
        const int32_t ret = buffer_utils_le_int32_t_get(buff);

        assert(INT32_MIN == ret);
    }
}

// Generated by ChatGPT
static void NO_COVERAGE test_buffer_utils_le_int64_t_get(void) {
    {
        // 0
        const char buff[8] = {
            0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00
        };
        const int64_t ret = buffer_utils_le_int64_t_get(buff);

        assert((int64_t)0 == ret);
    }
    {
        // positive: 0x1122334455667788
        const char buff[8] = {
            (char)0x88, 0x77, 0x66, 0x55,
            0x44, 0x33, 0x22, 0x11
        };
        const int64_t ret = buffer_utils_le_int64_t_get(buff);

        assert((int64_t)0x1122334455667788LL == ret);
    }
    {
        // negative: -2 = 0xFFFFFFFFFFFFFFFE
        const char buff[8] = {
            (char)0xFE, (char)0xFF, (char)0xFF, (char)0xFF,
            (char)0xFF, (char)0xFF, (char)0xFF, (char)0xFF
        };
        const int64_t ret = buffer_utils_le_int64_t_get(buff);

        assert((int64_t)-2 == ret);
    }
    {
        // INT64_MIN = 0x8000000000000000
        const char buff[8] = {
            0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, (char)0x80
        };
        const int64_t ret = buffer_utils_le_int64_t_get(buff);

        assert(INT64_MIN == ret);
    }
}

// Generated by ChatGPT
static void NO_COVERAGE test_buffer_utils_le_uint16_t_get(void) {
    {
        // 0
        const char buff[2] = { 0x00, 0x00 };
        const uint16_t ret = buffer_utils_le_uint16_t_get(buff);

        assert((uint16_t)0U == ret);
    }
    {
        // 0x1234
        const char buff[2] = { 0x34, 0x12 };
        const uint16_t ret = buffer_utils_le_uint16_t_get(buff);

        assert((uint16_t)0x1234U == ret);
    }
    {
        // UINT16_MAX = 0xFFFF
        const char buff[2] = { (char)0xFF, (char)0xFF };
        const uint16_t ret = buffer_utils_le_uint16_t_get(buff);

        assert(UINT16_MAX == ret);
    }
    {
        // high bit set: 0x8000
        const char buff[2] = { 0x00, (char)0x80 };
        const uint16_t ret = buffer_utils_le_uint16_t_get(buff);

        assert((uint16_t)0x8000U == ret);
    }
}

// Generated by ChatGPT
static void NO_COVERAGE test_buffer_utils_le_uint32_t_get(void) {
    {
        // 0
        const char buff[4] = { 0x00, 0x00, 0x00, 0x00 };
        const uint32_t ret = buffer_utils_le_uint32_t_get(buff);

        assert((uint32_t)0U == ret);
    }
    {
        // 0x12345678
        const char buff[4] = { 0x78, 0x56, 0x34, 0x12 };
        const uint32_t ret = buffer_utils_le_uint32_t_get(buff);

        assert((uint32_t)0x12345678UL == ret);
    }
    {
        // UINT32_MAX = 0xFFFFFFFF
        const char buff[4] = {
            (char)0xFF, (char)0xFF, (char)0xFF, (char)0xFF
        };
        const uint32_t ret = buffer_utils_le_uint32_t_get(buff);

        assert(UINT32_MAX == ret);
    }
    {
        // high bit set: 0x80000000
        const char buff[4] = { 0x00, 0x00, 0x00, (char)0x80 };
        const uint32_t ret = buffer_utils_le_uint32_t_get(buff);

        assert((uint32_t)0x80000000UL == ret);
    }
}

// Generated by ChatGPT
static void NO_COVERAGE test_buffer_utils_le_uint64_t_get(void) {
    {
        // 0
        const char buff[8] = {
            0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00
        };
        const uint64_t ret = buffer_utils_le_uint64_t_get(buff);

        assert((uint64_t)0ULL == ret);
    }
    {
        // 0x1122334455667788
        const char buff[8] = {
            (char)0x88, 0x77, 0x66, 0x55,
            0x44, 0x33, 0x22, 0x11
        };
        const uint64_t ret = buffer_utils_le_uint64_t_get(buff);

        assert((uint64_t)0x1122334455667788ULL == ret);
    }
    {
        // UINT64_MAX = 0xFFFFFFFFFFFFFFFF
        const char buff[8] = {
            (char)0xFF, (char)0xFF, (char)0xFF, (char)0xFF,
            (char)0xFF, (char)0xFF, (char)0xFF, (char)0xFF
        };
        const uint64_t ret = buffer_utils_le_uint64_t_get(buff);

        assert(UINT64_MAX == ret);
    }
    {
        // high bit set: 0x8000000000000000
        const char buff[8] = {
            0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, (char)0x80
        };
        const uint64_t ret = buffer_utils_le_uint64_t_get(buff);

        assert((uint64_t)0x8000000000000000ULL == ret);
    }
}
#endif
