/** @ingroup renderer_core
 *
 * @file renderer_memory.c
 * @author chocolate-pie24
 * @brief レンダラーレイヤーでのメモリ確保、メモリ解放処理のテストのため、memory_system内のallocate, free関数のラッパーAPIの実装
 *
 * @version 0.1
 * @date 2025-12-19
 *
 * @copyright Copyright (c) 2025 chocolate-pie24
 *
 * @par License
 * MIT License. See LICENSE file in the project root for full license text.
 *
 */
#include <stddef.h>

#include "engine/renderer/renderer_core/renderer_memory.h"
#include "engine/renderer/renderer_core/renderer_types.h"

#include "engine/renderer/renderer_core/renderer_err_utils.h"

#include "engine/core/memory/choco_memory.h"

// #define TEST_BUILD

#ifdef TEST_BUILD
// テスト時のみ使用するヘッダのinclude
#include <assert.h>
#include <string.h>
#include <stdlib.h>

#include "test_controller.h"
#include "engine/base/choco_macros.h"

#include "engine/renderer/renderer_core/test_renderer_memory.h"

#include "engine/core/memory/test_choco_memory.h"

// renderer_err_utils用モジュール専用テスト制御構造体定義

// 外部公開APIテスト設定
static test_call_control_t s_test_config_renderer_mem_allocate;   /**< renderer_mem_allocate()テスト設定 */

// プライベート関数テスト設定

// 全テスト関数プロトタイプ宣言
static void test_renderer_mem_allocate(void);
static void test_render_mem_free(void);
#endif

renderer_result_t renderer_mem_allocate(size_t size_, void** out_ptr_) {
#ifdef TEST_BUILD
    s_test_config_renderer_mem_allocate.call_count++;
    if(s_test_config_renderer_mem_allocate.fail_on_call != 0) {
        if(s_test_config_renderer_mem_allocate.call_count == s_test_config_renderer_mem_allocate.fail_on_call) {
            return (renderer_result_t)s_test_config_renderer_mem_allocate.forced_result;
        }
    }
#endif
    renderer_result_t ret = RENDERER_INVALID_ARGUMENT;

    memory_system_result_t ret_msys = memory_system_allocate(size_, MEMORY_TAG_RENDERER, out_ptr_);

    ret = renderer_rslt_convert_choco_memory(ret_msys);

    return ret;
}

void render_mem_free(void* ptr_, size_t size_) {
    memory_system_free(ptr_, size_, MEMORY_TAG_RENDERER);
}

#ifdef TEST_BUILD
void NO_COVERAGE test_renderer_mem_allocate_config_set(const test_call_control_t* config_) {
    if(NULL == config_) {
        assert(false);
        return;
    }
    s_test_config_renderer_mem_allocate.fail_on_call = config_->fail_on_call;
    s_test_config_renderer_mem_allocate.forced_result = config_->forced_result;
}

void NO_COVERAGE test_renderer_memory_config_reset(void) {
    test_call_control_reset(&s_test_config_renderer_mem_allocate);
}

void NO_COVERAGE test_renderer_memory(void) {
    test_renderer_mem_allocate();
    test_render_mem_free();
}

// Generated by ChatGPT
static void NO_COVERAGE test_renderer_mem_allocate(void) {
    {
        // renderer_mem_allocate() 冒頭で強制的に RENDERER_BAD_OPERATION を返させる
        renderer_result_t ret = RENDERER_UNDEFINED_ERROR;
        test_call_control_t config = { 0 };
        void* ptr = NULL;

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
        memory_system_destroy();

        test_call_control_reset(&config);
        config.fail_on_call = 1U;
        config.forced_result = (int)RENDERER_BAD_OPERATION;
        test_renderer_mem_allocate_config_set(&config);

        ret = renderer_mem_allocate(128U, &ptr);
        assert(RENDERER_BAD_OPERATION == ret);
        assert(NULL == ptr);

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
    }
    {
        // renderer_mem_allocate() の2回目呼び出しで強制的に RENDERER_LIMIT_EXCEEDED を返させる
        renderer_result_t ret = RENDERER_UNDEFINED_ERROR;
        test_call_control_t config = { 0 };
        void* ptr = NULL;

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
        memory_system_destroy();

        test_call_control_reset(&config);
        config.fail_on_call = 2U;
        config.forced_result = (int)RENDERER_LIMIT_EXCEEDED;
        test_renderer_mem_allocate_config_set(&config);

        ret = renderer_mem_allocate(128U, &ptr);
        assert(RENDERER_BAD_OPERATION == ret);
        assert(NULL == ptr);

        ret = renderer_mem_allocate(128U, &ptr);
        assert(RENDERER_LIMIT_EXCEEDED == ret);
        assert(NULL == ptr);

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
    }
    {
        // メモリシステム未初期化 -> RENDERER_BAD_OPERATION
        renderer_result_t ret = RENDERER_UNDEFINED_ERROR;
        void* ptr = NULL;

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
        memory_system_destroy();

        ret = renderer_mem_allocate(128U, &ptr);
        assert(RENDERER_BAD_OPERATION == ret);
        assert(NULL == ptr);

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
    }
    {
        // out_ptr_ == NULL -> RENDERER_INVALID_ARGUMENT
        renderer_result_t ret = RENDERER_UNDEFINED_ERROR;
        memory_system_result_t ret_msys = MEMORY_SYSTEM_INVALID_ARGUMENT;

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
        memory_system_destroy();

        ret_msys = memory_system_create();
        assert(MEMORY_SYSTEM_SUCCESS == ret_msys);

        ret = renderer_mem_allocate(128U, NULL);
        assert(RENDERER_INVALID_ARGUMENT == ret);

        memory_system_destroy();
        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
    }
    {
        // *out_ptr_ != NULL -> RENDERER_INVALID_ARGUMENT
        renderer_result_t ret = RENDERER_UNDEFINED_ERROR;
        memory_system_result_t ret_msys = MEMORY_SYSTEM_INVALID_ARGUMENT;
        void* ptr = malloc(8U);

        assert(NULL != ptr);

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
        memory_system_destroy();

        ret_msys = memory_system_create();
        assert(MEMORY_SYSTEM_SUCCESS == ret_msys);

        ret = renderer_mem_allocate(128U, &ptr);
        assert(RENDERER_INVALID_ARGUMENT == ret);
        assert(NULL != ptr);

        free(ptr);
        ptr = NULL;

        memory_system_destroy();
        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
    }
    {
        // size_ == 0 -> RENDERER_SUCCESS, *out_ptr_ は NULL のまま
        renderer_result_t ret = RENDERER_UNDEFINED_ERROR;
        memory_system_result_t ret_msys = MEMORY_SYSTEM_INVALID_ARGUMENT;
        void* ptr = NULL;

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
        memory_system_destroy();

        ret_msys = memory_system_create();
        assert(MEMORY_SYSTEM_SUCCESS == ret_msys);

        ret = renderer_mem_allocate(0U, &ptr);
        assert(RENDERER_SUCCESS == ret);
        assert(NULL == ptr);

        memory_system_destroy();
        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
    }
    {
        // 下位 memory_system_allocate() 冒頭で MEMORY_SYSTEM_RUNTIME_ERROR を返させる
        renderer_result_t ret = RENDERER_UNDEFINED_ERROR;
        test_call_control_t config = { 0 };
        void* ptr = NULL;

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
        memory_system_destroy();

        test_call_control_reset(&config);
        config.fail_on_call = 1U;
        config.forced_result = (int)MEMORY_SYSTEM_RUNTIME_ERROR;
        test_memory_system_allocate_config_set(&config);

        ret = renderer_mem_allocate(128U, &ptr);
        assert(RENDERER_RUNTIME_ERROR == ret);
        assert(NULL == ptr);

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
    }
    {
        // 下位 memory_system_allocate() 冒頭で MEMORY_SYSTEM_LIMIT_EXCEEDED を返させる
        renderer_result_t ret = RENDERER_UNDEFINED_ERROR;
        test_call_control_t config = { 0 };
        void* ptr = NULL;

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
        memory_system_destroy();

        test_call_control_reset(&config);
        config.fail_on_call = 1U;
        config.forced_result = (int)MEMORY_SYSTEM_LIMIT_EXCEEDED;
        test_memory_system_allocate_config_set(&config);

        ret = renderer_mem_allocate(128U, &ptr);
        assert(RENDERER_LIMIT_EXCEEDED == ret);
        assert(NULL == ptr);

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
    }
    {
        // 下位 memory_system_allocate() 冒頭で MEMORY_SYSTEM_NO_MEMORY を返させる
        renderer_result_t ret = RENDERER_UNDEFINED_ERROR;
        test_call_control_t config = { 0 };
        void* ptr = NULL;

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
        memory_system_destroy();

        test_call_control_reset(&config);
        config.fail_on_call = 1U;
        config.forced_result = (int)MEMORY_SYSTEM_NO_MEMORY;
        test_memory_system_allocate_config_set(&config);

        ret = renderer_mem_allocate(128U, &ptr);
        assert(RENDERER_NO_MEMORY == ret);
        assert(NULL == ptr);

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
    }
    {
        // 下位 memory_system_allocate() 冒頭で未定義値を返させる -> RENDERER_UNDEFINED_ERROR
        renderer_result_t ret = RENDERER_SUCCESS;
        test_call_control_t config = { 0 };
        void* ptr = NULL;

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
        memory_system_destroy();

        test_call_control_reset(&config);
        config.fail_on_call = 1U;
        config.forced_result = 99999;
        test_memory_system_allocate_config_set(&config);

        ret = renderer_mem_allocate(128U, &ptr);
        assert(RENDERER_UNDEFINED_ERROR == ret);
        assert(NULL == ptr);

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
    }
    {
        // 正常系
        renderer_result_t ret = RENDERER_UNDEFINED_ERROR;
        memory_system_result_t ret_msys = MEMORY_SYSTEM_INVALID_ARGUMENT;
        void* ptr = NULL;

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
        memory_system_destroy();

        ret_msys = memory_system_create();
        assert(MEMORY_SYSTEM_SUCCESS == ret_msys);

        ret = renderer_mem_allocate(128U, &ptr);
        assert(RENDERER_SUCCESS == ret);
        assert(NULL != ptr);

        memory_system_free(ptr, 128U, MEMORY_TAG_RENDERER);
        ptr = NULL;

        memory_system_destroy();
        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
    }
}

// Generated by ChatGPT
static void NO_COVERAGE test_render_mem_free(void) {
    {
        // メモリシステム未初期化 + NULL -> no-op
        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
        memory_system_destroy();

        render_mem_free(NULL, 128U);

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
    }
    {
        // 初期化済み + NULL -> no-op
        memory_system_result_t ret_msys = MEMORY_SYSTEM_INVALID_ARGUMENT;
        void* ptr = NULL;

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
        memory_system_destroy();

        ret_msys = memory_system_create();
        assert(MEMORY_SYSTEM_SUCCESS == ret_msys);

        ret_msys = memory_system_allocate(128U, MEMORY_TAG_RENDERER, &ptr);
        assert(MEMORY_SYSTEM_SUCCESS == ret_msys);
        assert(NULL != ptr);

        render_mem_free(NULL, 128U);

        memory_system_free(ptr, 128U, MEMORY_TAG_RENDERER);
        ptr = NULL;

        memory_system_destroy();
        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
    }
    {
        // size_ 不一致 -> 下位 memory_system_free() 側で no-op
        memory_system_result_t ret_msys = MEMORY_SYSTEM_INVALID_ARGUMENT;
        void* ptr = NULL;

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
        memory_system_destroy();

        ret_msys = memory_system_create();
        assert(MEMORY_SYSTEM_SUCCESS == ret_msys);

        ret_msys = memory_system_allocate(128U, MEMORY_TAG_RENDERER, &ptr);
        assert(MEMORY_SYSTEM_SUCCESS == ret_msys);
        assert(NULL != ptr);

        render_mem_free(ptr, 1024U);

        // no-op のはずなので、正しい条件で free できる
        memory_system_free(ptr, 128U, MEMORY_TAG_RENDERER);
        ptr = NULL;

        memory_system_destroy();
        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
    }
    {
        // render_mem_free() は MEMORY_TAG_RENDERER 固定で free することの確認
        // SYSTEM タグで確保した領域に対して呼ぶと no-op になり、その後 SYSTEM タグで正常に free できるはず
        memory_system_result_t ret_msys = MEMORY_SYSTEM_INVALID_ARGUMENT;
        void* ptr = NULL;

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
        memory_system_destroy();

        ret_msys = memory_system_create();
        assert(MEMORY_SYSTEM_SUCCESS == ret_msys);

        ret_msys = memory_system_allocate(128U, MEMORY_TAG_SYSTEM, &ptr);
        assert(MEMORY_SYSTEM_SUCCESS == ret_msys);
        assert(NULL != ptr);

        render_mem_free(ptr, 128U);

        // render_mem_free() が raw free しておらず、RENDERER タグ固定で no-op になっていればここで正常 free できる
        memory_system_free(ptr, 128U, MEMORY_TAG_SYSTEM);
        ptr = NULL;

        memory_system_destroy();
        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
    }
    {
        // 正常系: RENDERER タグで確保した領域を解放できる
        memory_system_result_t ret_msys = MEMORY_SYSTEM_INVALID_ARGUMENT;
        void* ptr = NULL;
        void* ptr2 = NULL;

        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
        memory_system_destroy();

        ret_msys = memory_system_create();
        assert(MEMORY_SYSTEM_SUCCESS == ret_msys);

        ret_msys = memory_system_allocate(128U, MEMORY_TAG_RENDERER, &ptr);
        assert(MEMORY_SYSTEM_SUCCESS == ret_msys);
        assert(NULL != ptr);

        render_mem_free(ptr, 128U);
        ptr = NULL;

        // free 後も引き続き renderer 領域を確保・解放できることを確認
        ret_msys = memory_system_allocate(64U, MEMORY_TAG_RENDERER, &ptr2);
        assert(MEMORY_SYSTEM_SUCCESS == ret_msys);
        assert(NULL != ptr2);

        render_mem_free(ptr2, 64U);
        ptr2 = NULL;

        memory_system_destroy();
        test_renderer_memory_config_reset();
        test_choco_memory_config_reset();
    }
}
#endif
