/** @ingroup camera_system
 *
 * @file camera_memory.c
 * @author chocolate-pie24
 * @brief カメラシステムレイヤー内でのメモリ確保/解放における実行結果コードと、メモリタグを統一化するため、choco_memoryモジュールのラップAPIの実装
 *
 * @version 0.1
 * @date 2026-03-19
 *
 * @copyright Copyright (c) 2026 chocolate-pie24
 *
 * @par License
 * MIT License. See LICENSE file in the project root for full license text.
 *
 */
#include <stddef.h>

#include "engine/camera_system/camera_core/camera_memory.h"

#include "engine/camera_system/camera_core/camera_err_utils.h"
#include "engine/camera_system/camera_core/camera_types.h"

#include "engine/core/memory/choco_memory.h"

// #define TEST_BUILD

#ifdef TEST_BUILD
// テスト時のみ使用するヘッダのinclude
#include <assert.h>
#include "test_controller.h"

#include "engine/base/choco_macros.h"

#include "engine/core/memory/test_choco_memory.h"

#include "engine/camera_system/camera_core/test_camera_memory.h"

// camera_memoryモジュール専用テスト制御構造体定義

// 外部公開APIテスト設定
static test_call_control_t s_test_config_camera_mem_allocate;   /**< camera_mem_allocate()テスト設定 */

// プライベート関数テスト設定

// 全テスト関数プロトタイプ宣言
static void test_camera_mem_allocate(void);
static void test_camera_mem_free(void);
#endif

camera_result_t camera_mem_allocate(size_t size_, void** out_ptr_) {
#ifdef TEST_BUILD
    s_test_config_camera_mem_allocate.call_count++;
    if(s_test_config_camera_mem_allocate.fail_on_call != 0) {
        if(s_test_config_camera_mem_allocate.call_count == s_test_config_camera_mem_allocate.fail_on_call) {
            return (camera_result_t)s_test_config_camera_mem_allocate.forced_result;
        }
    }
#endif
    camera_result_t ret = CAMERA_INVALID_ARGUMENT;
    memory_system_result_t ret_msys = memory_system_allocate(size_, MEMORY_TAG_CAMERA, out_ptr_);
    ret = camera_rslt_convert_choco_memory(ret_msys);

    return ret;
}

void camera_mem_free(void* ptr_, size_t size_) {
    memory_system_free(ptr_, size_, MEMORY_TAG_CAMERA);
}

#ifdef TEST_BUILD
void NO_COVERAGE test_camera_mem_allocate_config_set(const test_call_control_t* config_) {
    if(NULL == config_) {
        assert(false);
        return;
    }
    s_test_config_camera_mem_allocate.fail_on_call = config_->fail_on_call;
    s_test_config_camera_mem_allocate.forced_result = config_->forced_result;
}

void NO_COVERAGE test_camera_memory_config_reset(void) {
    test_call_control_reset(&s_test_config_camera_mem_allocate);
}

void NO_COVERAGE test_camera_memory(void) {
    test_camera_mem_allocate();
    test_camera_mem_free();
}

// Generated by ChatGPT 5.4 Thinking
static void NO_COVERAGE test_camera_mem_allocate(void) {
    {
        /* この関数自身の失敗注入が効くこと */
        camera_result_t ret = CAMERA_UNDEFINED_ERROR;
        test_call_control_t config = {0};
        void* ptr = NULL;

        test_camera_memory_config_reset();
        test_choco_memory_config_reset();
        test_call_control_reset(&config);

        config.fail_on_call = 1U;
        config.forced_result = (int)CAMERA_BAD_OPERATION;
        test_camera_mem_allocate_config_set(&config);

        ret = camera_mem_allocate(128U, &ptr);
        assert(CAMERA_BAD_OPERATION == ret);
        assert(NULL == ptr);

        test_camera_memory_config_reset();
    }
    {
        /* 正常系: 下位層まで到達して確保できること */
        memory_system_result_t ret_mem = MEMORY_SYSTEM_INVALID_ARGUMENT;
        camera_result_t ret = CAMERA_UNDEFINED_ERROR;
        void* ptr = NULL;

        test_camera_memory_config_reset();
        test_choco_memory_config_reset();

        ret_mem = memory_system_create();
        assert(MEMORY_SYSTEM_SUCCESS == ret_mem);

        ret = camera_mem_allocate(128U, &ptr);
        assert(CAMERA_SUCCESS == ret);
        assert(NULL != ptr);

        camera_mem_free(ptr, 128U);
        ptr = NULL;

        memory_system_destroy();
    }
}

// Generated by ChatGPT 5.4 Thinking
static void NO_COVERAGE test_camera_mem_free(void) {
    {
        /* 未初期化状態でも no-op で呼べること */
        test_camera_memory_config_reset();
        test_choco_memory_config_reset();

        camera_mem_free(NULL, 128U);
    }
    {
        /* camera_mem_allocate() で確保したメモリを解放できること */
        memory_system_result_t ret_mem = MEMORY_SYSTEM_INVALID_ARGUMENT;
        camera_result_t ret = CAMERA_UNDEFINED_ERROR;
        void* ptr = NULL;

        test_camera_memory_config_reset();
        test_choco_memory_config_reset();

        ret_mem = memory_system_create();
        assert(MEMORY_SYSTEM_SUCCESS == ret_mem);

        ret = camera_mem_allocate(128U, &ptr);
        assert(CAMERA_SUCCESS == ret);
        assert(NULL != ptr);

        camera_mem_free(ptr, 128U);
        ptr = NULL;

        memory_system_destroy();
    }
}
#endif
