#ifndef GLCE_ENGINE_SYSTEMS_RENDERER_RENDERER_RESOURCES_BUFFER_MANAGERS_BUFFER_MANAGER_TYPES_H
#define GLCE_ENGINE_SYSTEMS_RENDERER_RENDERER_RESOURCES_BUFFER_MANAGERS_BUFFER_MANAGER_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    BUFFER_MANAGER_SUCCESS = 0,
    BUFFER_MANAGER_INVALID_ARGUMENT,
    BUFFER_MANAGER_RUNTIME_ERROR,
    BUFFER_MANAGER_LIMIT_EXCEEDED,
    BUFFER_MANAGER_NO_MEMORY,
    BUFFER_MANAGER_DATA_CORRUPTED,
    BUFFER_MANAGER_BAD_OPERATION,
    BUFFER_MANAGER_OVERFLOW,
    BUFFER_MANAGER_UNDEFINED_ERROR,
} buffer_manager_result_t;

#ifdef __cplusplus
}
#endif
#endif
