title: "C言語とOpenGLで作るゲームエンジン開発(2Dレンダリング編 - Step4)"
summary: "本Bookでは、シンプルな三角形の描画とOpenGLの基礎について説明します。"
topics: ["c", "opengl", "glfw", "gameengine", "graphics"]
published: true
price: 0
chapters:
  - step4_0_introduction
  - step4_1_hello_triangle_overview
  - step4_2_opengl_coordinates
  - step4_3_buffer_explanation
  - step4_4_shader_explanation
  - step4_5_conclusion
