#ifndef GLCE_ENGINE_SYSTEMS_GEOMETRY_SYSTEM_GEOMETRY_SYSTEM_CORE_GEOMETRY_SYSTEM_ERR_UTILS_H
#define GLCE_ENGINE_SYSTEMS_GEOMETRY_SYSTEM_GEOMETRY_SYSTEM_CORE_GEOMETRY_SYSTEM_ERR_UTILS_H

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif
