#ifndef GLCE_ENGINE_CORE_GEOMETRY_PRIMITIVE_GEOMETRY_PRIMITIVE_TYPES_H
#define GLCE_ENGINE_CORE_GEOMETRY_PRIMITIVE_GEOMETRY_PRIMITIVE_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    GEOMETRY_PRIMITIVE_SUCCESS = 0,
    GEOMETRY_PRIMITIVE_INVALID_ARGUMENT,
    GEOMETRY_PRIMITIVE_RUNTIME_ERROR,
    GEOMETRY_PRIMITIVE_LIMIT_EXCEEDED,
    GEOMETRY_PRIMITIVE_BAD_OPERATION,
    GEOMETRY_PRIMITIVE_NO_MEMORY,
    GEOMETRY_PRIMITIVE_DATA_CORRUPTED,
    GEOMETRY_PRIMITIVE_UNDEFINED_ERROR,
} geometry_primitive_result_t;

#ifdef __cplusplus
}
#endif
#endif
