// SPDX-License-Identifier: MIT
// Copyright (c) 2026 chocolate-pie24

#ifndef GLCE_ENGINE_SYSTEMS_RENDERER_RENDER_RESOURCES_CORE_RENDER_RESOURCE_TYPES_H
#define GLCE_ENGINE_SYSTEMS_RENDERER_RENDER_RESOURCES_CORE_RENDER_RESOURCE_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    RENDER_RESOURCE_SUCCESS = 0,
    RENDER_RESOURCE_INVALID_ARGUMENT,
    RENDER_RESOURCE_RUNTIME_ERROR,
    RENDER_RESOURCE_NO_MEMORY,
    RENDER_RESOURCE_LIMIT_EXCEEDED,
    RENDER_RESOURCE_BAD_OPERATION,
    RENDER_RESOURCE_DATA_CORRUPTED,
    RENDER_RESOURCE_OVERFLOW,
    RENDER_RESOURCE_UNDEFINED_ERROR,
} render_resource_result_t;

#ifdef __cplusplus
}
#endif
#endif
