// SPDX-License-Identifier: MIT
// Copyright (c) 2026 chocolate-pie24

#ifndef GLCE_ENGINE_SYSTEMS_RENDERER_RESOURCES_TEXTURE_TEXTURE_GPU_RESOURCE_TYPES_H
#define GLCE_ENGINE_SYSTEMS_RENDERER_RESOURCES_TEXTURE_TEXTURE_GPU_RESOURCE_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    TEXTURE_GPU_RESOURCE_SUCCESS = 0,
    TEXTURE_GPU_RESOURCE_INVALID_ARGUMENT,
    TEXTURE_GPU_RESOURCE_RUNTIME_ERROR,
    TEXTURE_GPU_RESOURCE_NO_MEMORY,
    TEXTURE_GPU_RESOURCE_LIMIT_EXCEEDED,
    TEXTURE_GPU_RESOURCE_BAD_OPERATION,
    TEXTURE_GPU_RESOURCE_DATA_CORRUPTED,
    TEXTURE_GPU_RESOURCE_OVERFLOW,
    TEXTURE_GPU_RESOURCE_UNDEFINED_ERROR,
} texture_gpu_resource_result_t;

#ifdef __cplusplus
}
#endif
#endif
